# Generated by Django 3.1.7 on 2021-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_acad',
            name='certif',
            field=models.BooleanField(default=True, verbose_name='Posees Certificado'),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciudad '),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='instit',
            field=models.CharField(blank=True, max_length=25, verbose_name='Nombre de la institucion '),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='menc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mensión '),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='mod',
            field=models.IntegerField(blank=True, choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='nal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pais '),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='tipo_form',
            field=models.IntegerField(blank=True, choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='tit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Titulo obtenido '),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='token de validación '),
        ),
    ]
