# Generated by Django 3.1.7 on 2021-05-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_regusu', '0001_initial'),
        ('App_modadm', '0002_auto_20210507_1808'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valid_hab',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valid_hab',
            name='id_usu_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_usu_val', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usu_inf_prof',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usu_inf_pers',
            name='id_usu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usu_inf_pers',
            name='tipo_discap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.discapacidad'),
        ),
        migrations.AddField(
            model_name='usu_inf_contac',
            name='id_usu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usu_inf_apps',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usu_inf_apps',
            name='rol_sis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.rol'),
        ),
        migrations.AddField(
            model_name='usu_inf_acad',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_red_social',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_red_social',
            name='ls_red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.red_soc'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_prof_empleos',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_prof_empleos',
            name='ls_curs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.curs_dict'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_hab',
            name='id_hab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.habilidades'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_hab',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_form_acad',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_form_acad',
            name='ls_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.form_acad'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_contac_curs_dict',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_contac_curs_dict',
            name='ls_cursdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.curs_dict'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_apps_rol',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_apps_rol',
            name='rol_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.rol'),
        ),
        migrations.AddField(
            model_name='red_soc',
            name='id_usu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form_acad',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleos',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curs_dict',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app_reg_usu',
            name='app_mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.app_mod'),
        ),
    ]
