# Generated by Django 3.1.7 on 2021-05-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_regusu', '0002_auto_20210505_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='red_soc',
            name='id_usu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='red_soc',
            name='nombre_red',
            field=models.CharField(max_length=30, verbose_name='Nombre de la red '),
        ),
        migrations.AlterField(
            model_name='red_soc',
            name='usuario',
            field=models.CharField(max_length=20, verbose_name='nick o dirección de usuario'),
        ),
    ]
