# Generated by Django 3.1.7 on 2021-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_regusu', '0003_auto_20210506_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red_soc',
            name='uso',
            field=models.IntegerField(blank=True, choices=[(0, 'frecuente'), (1, 'moderado'), (2, 'poco frecuente'), (3, 'inactivo')], default=0, null=True),
        ),
    ]
