# Generated by Django 3.1.7 on 2021-05-06 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_regusu', '0005_auto_20210506_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='valid_hab',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valid_hab',
            name='id_usu_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_usu_val', to=settings.AUTH_USER_MODEL),
        ),
    ]
