# Generated by Django 3.1.7 on 2021-05-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_modadm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rl_func_app',
            old_name='ls_func',
            new_name='id_func',
        ),
    ]
