# Generated by Django 3.1.7 on 2021-05-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_modadm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='user_crear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_crear', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mod',
            name='user_modif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log_acc_mod',
            name='id_mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.mod'),
        ),
        migrations.AddField(
            model_name='app_mod',
            name='mod_prin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.mod'),
        ),
    ]
