# Generated by Django 3.1.7 on 2021-05-04 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_modpry', '0001_initial'),
        ('App_modadm', '0001_initial'),
        ('App_regusugr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipos_prog_inv',
            fields=[
                ('id_tipoprograma', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_tipoprogama', models.CharField(max_length=40, verbose_name='tipo de programa.')),
                ('desc_tipoprograma', models.CharField(max_length=40, verbose_name='Descripcion: ')),
            ],
            options={
                'verbose_name': 'tipos_prog_inv',
                'verbose_name_plural': 'tipos_prog_invs',
            },
        ),
        migrations.CreateModel(
            name='inf_prog_inv',
            fields=[
                ('id_inf_prog_inv', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_prog', models.CharField(max_length=40, verbose_name='codigo ')),
                ('nombre_archivo', models.CharField(max_length=40, verbose_name='Nombre  ')),
                ('url_archivo', models.URLField(verbose_name=' Url del archivo del proyecto.')),
                ('titulo_prog', models.CharField(max_length=40, verbose_name='Título del programa .  ')),
                ('num_inv', models.IntegerField(verbose_name='Número de investigadores(as) involucrados en el proyecto')),
                ('prom_frm', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0)),
                ('conv', models.CharField(max_length=40, verbose_name='Convenio propuesto  ')),
                ('dur', models.IntegerField(verbose_name='Duración del proyecto valores dentro de un rango.')),
                ('und_dur', models.IntegerField(choices=[(0, 'Seg'), (1, 'Min'), (2, 'Horas'), (3, 'Meses'), (4, 'Años')], default=0)),
                ('geo', models.CharField(max_length=40, verbose_name='Aŕea geográfica que abarca el progama.')),
                ('resu', models.TextField(verbose_name='Resumen del programa.')),
                ('url_ap', models.URLField(verbose_name=' Url de la imágen del árbol de problemas.')),
                ('url_ao', models.URLField(verbose_name='Url de la imágen del árbol de objetivos.')),
                ('pobl_bnd', models.IntegerField(verbose_name='Tamaño de la población beneficiaria directa del proyecto.')),
                ('pobl_bni', models.IntegerField(verbose_name='Tamaño de la población beneficiaria indirecta .')),
                ('obj_gen', models.CharField(max_length=40, verbose_name='Objetivo general del proyecto..')),
                ('obj_esp', models.CharField(max_length=40, verbose_name='Objetivos específicos del proyecto.')),
                ('id_grup_bd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusugr.usugr')),
                ('id_tipoprograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regprgi.tipos_prog_inv')),
            ],
            options={
                'verbose_name': 'inf_prog_inv',
                'verbose_name_plural': 'inf_prog_invs',
            },
        ),
        migrations.CreateModel(
            name='app_reg_prog_inv',
            fields=[
                ('id_app_reg_prog_inv', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_app_reg_pry', models.CharField(max_length=40, verbose_name='nombre de la App Registro ')),
                ('desc_app_reg_pry', models.CharField(max_length=40, verbose_name='Descripcion de la App ')),
                ('status_app_reg_pry', models.BooleanField(default=True, verbose_name='Estatus de la aplicacion')),
                ('id_mod_app', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.app_mod')),
                ('id_mod_pry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modpry.mod_pry')),
            ],
            options={
                'verbose_name': 'app_reg_prog_inv',
                'verbose_name_plural': 'app_reg_prog_invs',
            },
        ),
    ]
