# Generated by Django 3.1.7 on 2021-05-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_modadm', '0001_initial'),
        ('App_modpry', '0001_initial'),
        ('App_regprgi', '0001_initial'),
        ('App_regusugr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inf_prog_inv',
            name='id_grup_bd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusugr.usugr'),
        ),
        migrations.AddField(
            model_name='inf_prog_inv',
            name='id_tipoprograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regprgi.tipos_prog_inv'),
        ),
        migrations.AddField(
            model_name='app_reg_prog_inv',
            name='id_mod_app',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.app_mod'),
        ),
        migrations.AddField(
            model_name='app_reg_prog_inv',
            name='id_mod_pry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modpry.mod_pry'),
        ),
    ]
