# Generated by Django 3.2 on 2021-04-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm_install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='app_mod',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, verbose_name='Título de la aplicacion: ')),
                ('desc', models.CharField(max_length=80, verbose_name='descricion de la aplicacion: ')),
                ('url_doc', models.URLField(verbose_name='Direción local a la documentación o manual de la aplicación')),
                ('version', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Versión de desarrollo de la aplicación: ')),
                ('ver_mod', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Versión de desarrollo de la aplicación: ')),
                ('activo', models.BooleanField(default=False, verbose_name='estatus de la aplicacion ')),
                ('instalada', models.BooleanField(default=False, verbose_name='¿La aplicación se encuentra instalada? ')),
                ('visible', models.BooleanField(default=False, verbose_name='¿Activa o desactiva la visibilidad de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'app_mod',
                'verbose_name_plural': 'app_mods',
            },
        ),
        migrations.CreateModel(
            name='ext_app',
            fields=[
                ('id_app_ext', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_app_ext', models.CharField(max_length=40, verbose_name='Título de la aplicacion: ')),
                ('mod_prin_app_ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
            ],
            options={
                'verbose_name': 'ext_app',
                'verbose_name_plural': 'ext_apps',
            },
        ),
        migrations.CreateModel(
            name='ext_mod',
            fields=[
                ('id_mod_ext', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_ext', models.CharField(max_length=40, verbose_name='Título de la aplicacion: ')),
            ],
            options={
                'verbose_name': 'ext_mod',
                'verbose_name_plural': 'ext_mods',
            },
        ),
        migrations.CreateModel(
            name='fuente_ins',
            fields=[
                ('id_rep', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('0', 'Cédula de Ciudadanía'), ('1', 'Tarjeta de Identidad'), ('2', 'Cédula de Extranjería'), ('3', 'Pasaporte'), ('4', 'Permiso de Residencia')], default='0', max_length=1)),
                ('tipo_arch', models.CharField(choices=[('0', '.Zip'), ('1', '.Gz'), ('2', '.ded'), ('3', '.exe'), ('4', 'otro')], default='0', max_length=1)),
                ('url_loc', models.CharField(max_length=5, verbose_name='Drección local : ')),
                ('url_rem', models.URLField(verbose_name='Drección remota ')),
                ('url', models.URLField(verbose_name='Drección local relativa ')),
                ('valid', models.BooleanField(default=False, verbose_name='¿fuente valida?')),
            ],
            options={
                'verbose_name': 'fuente_ins',
                'verbose_name_plural': 'fuente_inss',
            },
        ),
        migrations.CreateModel(
            name='func_app',
            fields=[
                ('id_func', models.AutoField(primary_key=True, serialize=False)),
                ('nom_func', models.CharField(max_length=30, verbose_name='Nombre de la función: ')),
                ('lib_func', models.CharField(max_length=30, verbose_name='Librería que contiene la función: ')),
                ('url_loc', models.URLField(verbose_name='Direción local a la documentación o manual de la aplicación')),
                ('com_exc', models.CharField(max_length=20, verbose_name='Comando de Ejecución de la Función: ')),
                ('text', models.CharField(max_length=20, verbose_name='Nombre de Función: ')),
                ('context', models.CharField(max_length=20, verbose_name='Contexto: ')),
                ('activa', models.BooleanField(default=False, verbose_name='¿Activa o desactiva.?')),
                ('indice', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'func_app',
                'verbose_name_plural': 'func_apps',
            },
        ),
        migrations.CreateModel(
            name='listado_aplicativo',
            fields=[
                ('id_aplicativo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_aplicativo', models.CharField(max_length=30, verbose_name='permisos: ')),
                ('activoaplicativo', models.BooleanField(default=False, verbose_name='¿Activo o desactivo.?')),
            ],
            options={
                'verbose_name': 'listado_aplicativo',
                'verbose_name_plural': 'listado_aplicativo',
            },
        ),
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, verbose_name='Título del módulo')),
                ('desc', models.CharField(max_length=50, verbose_name='descripcion del Módulo')),
                ('url_doc', models.URLField(verbose_name='Sitio url')),
                ('version', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Versión de desarrollo ')),
                ('activo', models.BooleanField(default=False, verbose_name='Status del Modulo ')),
                ('instalado', models.BooleanField(default=False, verbose_name='¿el módulo se encuentra instalado?')),
                ('visible', models.BooleanField(default=False, verbose_name='¿Activa o desactiva la visibilidad de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'mod',
                'verbose_name_plural': 'mods',
            },
        ),
        migrations.CreateModel(
            name='param_config',
            fields=[
                ('id_param_config', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_param_config', models.CharField(max_length=40, verbose_name='Parametro ')),
            ],
            options={
                'verbose_name': 'param_config',
                'verbose_name_plural': 'param_configs',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permisos', models.AutoField(primary_key=True, serialize=False)),
                ('nom_permiso', models.CharField(max_length=30, verbose_name='permisos: ')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Activ o desactivo.?')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('etq_rol', models.CharField(max_length=30, verbose_name='Etiqueta: ')),
                ('desc', models.CharField(max_length=30, verbose_name='Descripcion del Rol: ')),
                ('tipo', models.CharField(choices=[('0', 'Sistema'), ('1', 'Módulo'), ('2', 'Aplicación'), ('3', 'Extensión'), ('4', 'Otro')], default='0', max_length=1)),
                ('req_reg', models.BooleanField(default=False, verbose_name='¿Activa o desactiva.?')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
                ('id_ext_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.ext_app')),
                ('id_ext_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.ext_mod')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('id_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.listado_aplicativo')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'rols',
            },
        ),
        migrations.CreateModel(
            name='usu',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30, verbose_name='Nick: ')),
                ('passusu', models.CharField(max_length=30, verbose_name='Contraseña: ')),
                ('fch_regi', models.DateField(verbose_name='fecha de registro')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Activo o desactivado.?')),
                ('id_rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
            options={
                'verbose_name': 'usu',
                'verbose_name_plural': 'usus',
            },
        ),
        migrations.CreateModel(
            name='rol_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Activ o desactivo.?')),
                ('id_permisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
            options={
                'verbose_name': 'rol_permiso',
                'verbose_name_plural': 'rol_permisos',
            },
        ),
        migrations.CreateModel(
            name='rl_mod_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('ls_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_param_cnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('ls_param_cnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.param_config')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('ls_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.func_app')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_app_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('ls_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
            ],
        ),
        migrations.CreateModel(
            name='rl_fuente_ins_param_cnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_param_cnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.param_config')),
                ('id_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.fuente_ins')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
                ('ls_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_param_cnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
                ('ls_param_cnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.param_config')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
                ('ls_mods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
                ('ls_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.func_app')),
            ],
        ),
        migrations.CreateModel(
            name='mod_adm',
            fields=[
                ('sesion', models.AutoField(primary_key=True, serialize=False)),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('id_usu_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'mod_adm',
                'verbose_name_plural': 'mod_adms',
            },
        ),
        migrations.CreateModel(
            name='log_mod_rol',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.URLField(verbose_name='Drección local relativa ')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
            ],
            options={
                'verbose_name': 'log_mod_rol',
                'verbose_name_plural': 'log_mod_rols',
            },
        ),
        migrations.CreateModel(
            name='log_acc_pltf',
            fields=[
                ('id_acc_pltf', models.AutoField(primary_key=True, serialize=False)),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de fin')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'log_acc_pltf',
                'verbose_name_plural': 'log_acc_pltfs',
            },
        ),
        migrations.CreateModel(
            name='log_acc_mod',
            fields=[
                ('id_log_acces', models.AutoField(primary_key=True, serialize=False)),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de fin')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'log_acc_mod',
                'verbose_name_plural': 'log_acc_mods',
            },
        ),
        migrations.AddField(
            model_name='ext_mod',
            name='mod_prin_ext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod'),
        ),
        migrations.AddField(
            model_name='app_mod',
            name='mod_prin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod'),
        ),
    ]
