# Generated by Django 3.2 on 2021-04-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administr', '0002_app_reg_usu_curs_dict_discapacidad_empleos_form_acad_habilidades_red_soc_rl_usu_inf_apps_rol_rl_usu_'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_reg_gr',
            fields=[
                ('id_app_reg_gr', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='Descripcion.')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.app_mod')),
            ],
            options={
                'verbose_name': 'app_reg_gr',
                'verbose_name_plural': 'app_reg_grs',
            },
        ),
        migrations.CreateModel(
            name='app_reg_ins',
            fields=[
                ('app_reg_ins', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_app_reg_ins', models.CharField(max_length=20, verbose_name='Nombre  ')),
                ('desc_app_reg_ins', models.CharField(max_length=20, verbose_name='Descripcion  ')),
                ('status_app_reg_ins', models.BooleanField(default=False, verbose_name='Activo ')),
                ('id_aplicacion_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.mod')),
            ],
            options={
                'verbose_name': 'app_reg_ins',
                'verbose_name_plural': 'app_reg_inss',
            },
        ),
        migrations.CreateModel(
            name='conv_inv',
            fields=[
                ('id_conv', models.AutoField(primary_key=True, serialize=False)),
                ('val_min', models.PositiveSmallIntegerField(default=5, verbose_name='valor minimo: ')),
                ('val_max', models.PositiveSmallIntegerField(default=5, verbose_name='valor maximo: ')),
                ('fch_ini', models.DateField(verbose_name='Fecha de inicio Incripciones: ')),
                ('fch_fin', models.DateField(verbose_name='Fecha de Cierre de Inscripciones: ')),
                ('pltf', models.BooleanField(default=False, verbose_name='Se puede registrar desde la plataforma: ')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad ')),
                ('mod', models.CharField(choices=[('0', 'Presencial'), ('1', 'Virtual'), ('2', 'Semipresencial'), ('3', 'A distancia'), ('4', 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Modalidad ')),
                ('und_acdm', models.CharField(max_length=60, verbose_name='Nombre de la unidad académica ')),
                ('resp', models.CharField(max_length=60, verbose_name='Nombre de la persona responsable ')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo ')),
                ('nom_conv', models.CharField(max_length=60, verbose_name='Nombre de la convocatori ')),
                ('url_conv', models.URLField(max_length=80, verbose_name='sitio web donde se puede localizar los términos de al convocatoria')),
                ('url_insc', models.URLField(max_length=80, verbose_name='Url del formulario de inscripción')),
            ],
            options={
                'verbose_name': 'conv_inv',
                'verbose_name_plural': 'conv_invs',
            },
        ),
        migrations.CreateModel(
            name='curs_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instit', models.CharField(max_length=20, verbose_name='Nombre de la institucion académica ')),
                ('tipo_form_gr', models.CharField(choices=[('0', 'Seminario'), ('1', 'Taller'), ('2', 'Foro'), ('3', 'Charla'), ('4', 'Encuentro'), ('5', 'Simposio'), ('6', 'Panel'), ('7', 'Conferencia'), ('8', 'Diplomado'), ('9', 'Curso Corto'), ('10', 'Congreso'), ('11', 'Socialización'), ('12', 'Coloquio'), ('13', 'Otro')], default='0', max_length=2)),
                ('fch_ini', models.DateField(verbose_name='fecha Inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha Fin ')),
                ('certif', models.BooleanField(default=True, verbose_name='Activo ')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais: ')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad ')),
                ('mod', models.CharField(choices=[('0', 'Presencial'), ('1', 'Virtual'), ('2', 'Semipresencial'), ('3', 'A distancia'), ('4', 'Aprendizaje Acompañado')], default=0, max_length=1)),
                ('num_est', models.PositiveSmallIntegerField(default=5, verbose_name='Cupo de Estudiantes o asistentes')),
                ('dur', models.PositiveSmallIntegerField(default=5, verbose_name='Número total de horas académicas del curso')),
                ('nom_curs', models.CharField(max_length=30, verbose_name='Nombre del Curso o evento académico. ')),
                ('mun_ciclos', models.PositiveSmallIntegerField(default=5, verbose_name='cuántas veces se realizará el curso o evento')),
                ('url_prog', models.URLField(verbose_name='página web o blog del grupo ')),
                ('inscr', models.URLField(null='False', verbose_name='Url del formulario de inscripción.')),
            ],
            options={
                'verbose_name': 'curs_ofer',
                'verbose_name_plural': 'curs_ofers',
            },
        ),
        migrations.CreateModel(
            name='etapa_gr',
            fields=[
                ('id_etp_gr', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20, verbose_name='Nombre del grupo  ')),
                ('fch_ini_nom', models.DateField(verbose_name='Fecha en la que se creó el grupo ')),
                ('fch_fin_nom', models.DateField(verbose_name='Fecha en la que se terminó el grupo')),
                ('vig', models.BooleanField(default=True, verbose_name='El nombre se encuentra vigente ')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla con la que se identificó(a) el grupo ')),
                ('url_arch', models.URLField(verbose_name='URL del sitio web ')),
                ('gruplac', models.URLField(blank='False', null='False', verbose_name='Url del GrupLac del grupo de Investigación con ese nombre si se está registrado en esa plataforma.')),
            ],
            options={
                'verbose_name': 'etapa_gr',
                'verbose_name_plural': 'etapa_grs',
            },
        ),
        migrations.CreateModel(
            name='form_acad_gr',
            fields=[
                ('id_form_acad_gr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_form', models.CharField(choices=[('0', 'Seminario'), ('1', 'Taller'), ('2', 'Foro'), ('3', 'Charla'), ('4', 'Encuentro'), ('5', 'Simposio'), ('6', 'Panel'), ('7', 'Conferencia'), ('8', 'Diplomado'), ('9', 'Curso Corto'), ('10', 'Congreso'), ('11', 'Socialización'), ('12', 'Coloquio'), ('13', 'Otro')], default='0', max_length=2)),
                ('fch_ini', models.DateField(verbose_name='Fecha de inicio ')),
                ('fch_fin', models.DateField(verbose_name='Fecha de fin: ')),
                ('certif', models.BooleanField(default=True, verbose_name='Posees Ceertificado: ')),
                ('nal', models.CharField(max_length=25, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=25, verbose_name='Ciudad: ')),
                ('mod', models.CharField(choices=[('0', 'Presencial'), ('1', 'Virtual'), ('2', 'Semipresencial'), ('3', 'A distancia'), ('4', 'Aprendizaje Acompañado')], default='0', max_length=1)),
                ('asis', models.PositiveSmallIntegerField(default=5, verbose_name='Número de asistentes')),
                ('hora', models.PositiveSmallIntegerField(default=5, verbose_name=' Número de horas académicas')),
                ('mem', models.URLField(verbose_name='url de las memorias del tipo de formación')),
                ('token', models.CharField(max_length=30, verbose_name='Token de validación electrónica')),
            ],
            options={
                'verbose_name': 'form_acad_gr',
                'verbose_name_plural': 'form_acad_gr',
            },
        ),
        migrations.CreateModel(
            name='prog_ofer',
            fields=[
                ('id_prog', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_form', models.CharField(choices=[('0', 'Universitaria'), ('1', 'Especializacion'), ('2', 'Maestría'), ('3', 'Doctorado'), ('4', 'PHD'), ('5', 'Posdoctorado'), ('6', 'Básica Secundaria'), ('7', 'Básica Primaria'), ('8', 'Diplomado'), ('9', 'Curso Corto'), ('10', 'Técnica'), ('11', 'tecnológica'), ('12', 'Curso libre')], max_length=2)),
                ('fch_ini', models.DateField(verbose_name='fecha de inscripcion')),
                ('fch_fin', models.DateField(verbose_name='fecha de Cierre de la inscripcion')),
                ('certif', models.BooleanField(default=True, verbose_name='Posee certificado')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais: ')),
                ('ciudad', models.CharField(max_length=40, verbose_name='Ciudad ')),
                ('mod', models.CharField(choices=[('0', 'Presencial'), ('1', 'Virtual'), ('2', 'Semipresencial'), ('3', 'A distancia'), ('4', 'Aprendizaje Acompañado')], max_length=1, verbose_name='MODALIDAD')),
                ('num_est', models.PositiveSmallIntegerField(default=5, verbose_name='cantidad d estudiantes ')),
                ('dur', models.PositiveSmallIntegerField(default=4, verbose_name='Número total de horas')),
                ('dur_sem', models.PositiveSmallIntegerField(default=4, verbose_name='Número total de semestres')),
                ('nom_prog', models.CharField(max_length=30, verbose_name='Nombre del Programa')),
                ('acred', models.BooleanField(default=True, verbose_name='El programa se encuentra acreditado')),
                ('ven_acrd', models.PositiveSmallIntegerField(default=5, verbose_name='Año de vencimiento de la acreditación')),
                ('url_prog', models.URLField(max_length=80, verbose_name='sitio web donde se puede localizar el programa')),
            ],
            options={
                'verbose_name': 'prog_ofer',
                'verbose_name_plural': 'prog_ofers',
            },
        ),
        migrations.CreateModel(
            name='rel_usugr_ls_etp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rel_usugr_ls_usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rel_usugr_ls_usu_nr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_form_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
                ('ls_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.form_acad')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
                ('ls_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.red_soc')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usugr_inf_rol_Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usui_conv_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usui_usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usui_usugr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='usu_nr',
            fields=[
                ('id_usu_nr', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres del integrante no registrado(a).')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos del integrante no registrado(a).')),
                ('cvlac', models.URLField(verbose_name='URL del CVlac del investigador(a).')),
                ('orcid', models.CharField(max_length=20, verbose_name='ID de ORCID del investigador(a).')),
                ('ggl', models.URLField(verbose_name='URL Google académico del investigador(a)')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
            options={
                'verbose_name': 'usu_nr',
                'verbose_name_plural': 'usu_nrs',
            },
        ),
        migrations.CreateModel(
            name='usugr',
            fields=[
                ('id_gr', models.AutoField(primary_key=True, serialize=False)),
                ('passgr', models.CharField(max_length=20, verbose_name='Descripcion ')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo ')),
                ('id_rol_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
                ('id_usu_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'usugr',
                'verbose_name_plural': 'usugr',
            },
        ),
        migrations.CreateModel(
            name='usugr_curs_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='usugr_form_acad_gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='usugr_inf_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'usugr_inf_acad',
                'verbose_name_plural': 'usugr_inf_acads',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.listado_aplicativo')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
            options={
                'verbose_name': 'usugr_inf_apps',
                'verbose_name_plural': 'usugr_inf_appss',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_nal', models.CharField(max_length=20, verbose_name='Nacionalidad ')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefono oficina ')),
                ('cel', models.CharField(max_length=20, verbose_name='N° Celular ')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('cod_post', models.PositiveSmallIntegerField(default=5, verbose_name='Codigo Postal ')),
                ('ls_hr', models.CharField(choices=[('0', '8am 12pm'), ('1', '2pm 6pm'), ('2', '8am 12pm - 2pm 6pm')], default='0', max_length=1)),
                ('web', models.URLField(verbose_name='página web o blog del grupo ')),
                ('dir_offi', models.TextField(verbose_name='Direccion e oficina')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr')),
            ],
            options={
                'verbose_name': 'usugr_inf_contac',
                'verbose_name_plural': 'usugr_inf_contacs',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_gr',
            fields=[
                ('id_usugr', models.AutoField(primary_key=True, serialize=False)),
                ('cod_gr', models.PositiveSmallIntegerField(default=8, verbose_name=' código único de identificación del grupo')),
                ('tipo_gr', models.CharField(choices=[('0', 'Independiente'), ('1', 'Reconocido Inst'), ('2', 'Reconocido COLC'), ('3', 'Semillero de Inv.'), ('4', 'Comunidad'), ('5', 'Estado del Arte')], default=0, max_length=1)),
                ('nal', models.CharField(max_length=40, verbose_name='Nacionalidad')),
                ('dir', models.CharField(max_length=40, verbose_name='Direccion de correspondencia ')),
                ('estado', models.CharField(choices=[('0', 'Creado'), ('1', 'Desarrollo Temprano'), ('2', 'Dearrollo Medio'), ('3', 'Desarrollo Alto'), ('4', 'Consolidado'), ('5', 'Ramificado'), ('6', 'Fusionado'), ('7', 'Disgregado'), ('8', 'Disuelto'), ('9', 'liquidado'), ('10', 'Abandonado')], default=0, max_length=2)),
                ('url_imag', models.URLField(verbose_name='url de la imagen o logo del grupo')),
                ('zona_hor', models.CharField(max_length=40, verbose_name='Zona Horaria')),
                ('id_etp_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.etapa_gr')),
            ],
            options={
                'verbose_name': 'usugr_inf_gr',
                'verbose_name_plural': 'usugr_inf_grs',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr_inf_gr')),
                ('ls_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.red_soc')),
            ],
        ),
        migrations.CreateModel(
            name='usui',
            fields=[
                ('id_usuinst', models.AutoField(primary_key=True, serialize=False)),
                ('passinst', models.CharField(max_length=15, verbose_name='Contraseña ')),
                ('fch_regi', models.DateField(verbose_name='fecha de registro de usurio: ')),
                ('activo', models.BooleanField(default=True, verbose_name=' estatus del usuario activo')),
                ('id_rol_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
                ('id_usu_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'usui',
                'verbose_name_plural': 'usuis',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelform', models.CharField(choices=[('0', 'Universitaria'), ('1', 'Especializacion'), ('2', 'Maestría'), ('3', 'Doctorado'), ('4', 'PHD'), ('5', 'Posdoctorado'), ('6', 'Básica Secundaria'), ('7', 'Básica Primaria'), ('8', 'Diplomado'), ('9', 'Curso Corto'), ('10', 'Técnica'), ('11', 'tecnológica'), ('12', 'Curso libre')], max_length=2, verbose_name='Nivel de formacion ')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
            ],
            options={
                'verbose_name': 'usui_inf_acad',
                'verbose_name_plural': 'usui_inf_acads',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.listado_aplicativo')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
            options={
                'verbose_name': 'usui_inf_apps',
                'verbose_name_plural': 'usui_inf_appss',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_nal', models.CharField(max_length=5, verbose_name='Indicativo telefónico de país')),
                ('tel', models.CharField(max_length=20, verbose_name='Número de telefono fijo')),
                ('cel', models.CharField(max_length=20, verbose_name='Número de telefono móvil')),
                ('email', models.EmailField(max_length=40, verbose_name='correo ')),
                ('cod_post', models.PositiveSmallIntegerField(default=8, verbose_name='código postal ')),
                ('ls_ha', models.CharField(choices=[('0', '8am 12pm'), ('1', '2pm 6pm'), ('2', '8am 12pm - 2pm 6pm')], default=0, max_length=1)),
                ('web', models.URLField(max_length=60, verbose_name=' dirección de página web o blog institucional')),
                ('dir_pri', models.TextField(verbose_name='Dirección de sede principal (país, ciudad, dir. ')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
            ],
            options={
                'verbose_name': 'usui_inf_contac',
                'verbose_name_plural': 'usui_inf_contacs',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuii', models.CharField(max_length=30, verbose_name='número único de identificación institucional sin puntos')),
                ('tipo_nuii', models.CharField(choices=[('0', 'NIT'), ('1', 'RUT')], default=0, max_length=1, verbose_name='Tipo de Número de identificación Institucional')),
                ('rs', models.CharField(max_length=30, verbose_name='Razón Social de la Institución')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla institucional')),
                ('repleg', models.CharField(max_length=60, verbose_name='Nombre Completo del representante legal')),
                ('nal', models.CharField(max_length=25, verbose_name='nacionalidad')),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio de la institución')),
                ('fch_reg', models.DateField(verbose_name='fecha de registro de la institución en al plataforma')),
                ('tipo_inst', models.CharField(choices=[('0', 'Cédula de Ciudadanía'), ('1', 'Tarjeta de Identidad'), ('2', 'Cédula de Extranjería'), ('3', 'Pasaporte'), ('4', 'Permiso de Residencia')], default=0, max_length=1, verbose_name='Tipo de institución o entidad')),
                ('sector', models.CharField(choices=[('0', 'Privado'), ('1', 'Publico'), ('2', 'xxx'), ('3', 'zzzz')], default=0, max_length=1, verbose_name='sector de desempeño de la entidad o institución ')),
                ('dir', models.TextField(verbose_name='direccion sede administrativa')),
                ('url_imag', models.URLField(verbose_name='url de la imagen institucional o logo')),
                ('zona_hor', models.CharField(max_length=60, verbose_name='Zona Horario internacional')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
            ],
            options={
                'verbose_name': 'usui_inf_inst',
                'verbose_name_plural': 'usui_inf_insts',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
            ],
        ),
        migrations.CreateModel(
            name='usui_red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.red_soc')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
            ],
        ),
        migrations.CreateModel(
            name='usui_rol_actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol')),
            ],
        ),
        migrations.CreateModel(
            name='usuo_prog_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.prog_ofer')),
            ],
        ),
        migrations.AddField(
            model_name='rl_app_mod_rol',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.DeleteModel(
            name='rl_usu_inf_contac_red_social',
        ),
        migrations.AddField(
            model_name='usugr_inf_acad',
            name='id_usugr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr_inf_gr'),
        ),
        migrations.AddField(
            model_name='usugr_form_acad_gr',
            name='id_usugr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr_inf_gr'),
        ),
        migrations.AddField(
            model_name='usugr_form_acad_gr',
            name='ls_form_gr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.form_acad_gr'),
        ),
        migrations.AddField(
            model_name='usugr_curs_ofer',
            name='id_usugr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr_inf_gr'),
        ),
        migrations.AddField(
            model_name='usugr_curs_ofer',
            name='ls_cursofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.curs_ofer'),
        ),
        migrations.AddField(
            model_name='rl_usui_usugr',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_usugr',
            name='ls_usugr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr'),
        ),
        migrations.AddField(
            model_name='rl_usui_usu',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_usu',
            name='ls_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu'),
        ),
        migrations.AddField(
            model_name='rl_usui_conv_inv',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_conv_inv',
            name='ls_conv_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.conv_inv'),
        ),
        migrations.AddField(
            model_name='rl_usugr_inf_rol_actual',
            name='id_usugr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr'),
        ),
        migrations.AddField(
            model_name='rl_usugr_inf_rol_actual',
            name='rol_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.rol'),
        ),
        migrations.AddField(
            model_name='rel_usugr_ls_usu_nr',
            name='id_gr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr'),
        ),
        migrations.AddField(
            model_name='rel_usugr_ls_usu_nr',
            name='ls_int_nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu_nr'),
        ),
        migrations.AddField(
            model_name='rel_usugr_ls_usu',
            name='id_gr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr'),
        ),
        migrations.AddField(
            model_name='rel_usugr_ls_usu',
            name='ls_int_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu'),
        ),
        migrations.AddField(
            model_name='rel_usugr_ls_etp',
            name='id_gr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usugr'),
        ),
        migrations.AddField(
            model_name='rel_usugr_ls_etp',
            name='ls_etp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.etapa_gr'),
        ),
        migrations.AddField(
            model_name='prog_ofer',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui'),
        ),
        migrations.AddField(
            model_name='conv_inv',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usui'),
        ),
    ]
