# Generated by Django 3.2 on 2021-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administr', '0003_auto_20210413_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conv_inv',
            name='mod',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Modalidad '),
        ),
        migrations.AlterField(
            model_name='curs_dict',
            name='dur',
            field=models.IntegerField(verbose_name='Cantidad de estudiantes'),
        ),
        migrations.AlterField(
            model_name='curs_dict',
            name='mod',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='curs_dict',
            name='mun_ciclos',
            field=models.IntegerField(verbose_name='cuántas veces se dictó el curso'),
        ),
        migrations.AlterField(
            model_name='curs_dict',
            name='nom_curs',
            field=models.CharField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Número total de horas académicas del curso'),
        ),
        migrations.AlterField(
            model_name='curs_dict',
            name='tipo_form',
            field=models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='curs_ofer',
            name='mod',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='curs_ofer',
            name='tipo_form_gr',
            field=models.IntegerField(choices=[(0, 'Seminario'), (1, 'Taller'), (2, 'Foro'), (3, 'Charla'), (4, 'Encuentro'), (5, 'Simposio'), (6, 'Panel'), (7, 'Conferencia'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Congreso'), (11, 'Socialización'), (12, 'Coloquio'), (13, 'Otro')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='empleos',
            name='tipo_contr',
            field=models.IntegerField(choices=[(0, 'Término Indefinido'), (1, 'Término Fijo'), (2, 'Temporal'), (3, 'Orden de Servicio'), (4, 'Contrato de Obra'), (5, 'Asesoría'), (6, 'Consultoría'), (7, 'independiente')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='mod',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='form_acad',
            name='tipo_form',
            field=models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='form_acad_gr',
            name='mod',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='form_acad_gr',
            name='tipo_form',
            field=models.IntegerField(choices=[(0, 'Seminario'), (1, 'Taller'), (2, 'Foro'), (3, 'Charla'), (4, 'Encuentro'), (5, 'Simposio'), (6, 'Panel'), (7, 'Conferencia'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Congreso'), (11, 'Socialización'), (12, 'Coloquio'), (13, 'Otro')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='fuente_ins',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='fuente_ins',
            name='tipo_arch',
            field=models.IntegerField(choices=[(0, '.Zip'), (1, '.Gz'), (2, '.ded'), (3, '.exe'), (4, 'otro')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='fuente_ins',
            name='url_loc',
            field=models.CharField(max_length=5, verbose_name='Dirección local: '),
        ),
        migrations.AlterField(
            model_name='listado_aplicativo',
            name='nom_aplicativo',
            field=models.CharField(max_length=30, verbose_name='aplicativo nombre: '),
        ),
        migrations.AlterField(
            model_name='prog_ofer',
            name='mod',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='MODALIDAD'),
        ),
        migrations.AlterField(
            model_name='prog_ofer',
            name='tipo_form',
            field=models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Sistema'), (1, 'Módulo'), (2, 'Aplicación'), (3, 'Extensión'), (4, 'Otro')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usu_inf_acad',
            name='nivelform',
            field=models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='usu_inf_contac',
            name='ls_ha',
            field=models.IntegerField(choices=[(0, '8am 12pm'), (1, '2pm 6pm'), (2, '8am 12pm - 2pm 6pm')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='gene',
            field=models.IntegerField(choices=[(0, 'Neutro'), (1, 'Femenino'), (2, 'Masculino'), (3, 'Intergénero'), (4, 'Transgénero'), (5, 'Sisgénero'), (6, 'Otro')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='tipo_nuip',
            field=models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usugr_inf_contac',
            name='ls_hr',
            field=models.IntegerField(choices=[(0, '8am 12pm'), (1, '2pm 6pm'), (2, '8am 12pm - 2pm 6pm')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usugr_inf_gr',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Creado'), (1, 'Desarrollo Temprano'), (2, 'Dearrollo Medio'), (3, 'Desarrollo Alto'), (4, 'Consolidado'), (5, 'Ramificado'), (6, 'Fusionado'), (7, 'Disgregado'), (8, 'Disuelto'), (9, 'liquidado'), (10, 'Abandonado')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='usugr_inf_gr',
            name='tipo_gr',
            field=models.IntegerField(choices=[(0, 'Independiente'), (1, 'Reconocido Inst'), (2, 'Reconocido COLC'), (3, 'Semillero de Inv.'), (4, 'Comunidad'), (5, 'Estado del Arte')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usui_inf_acad',
            name='nivelform',
            field=models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2, verbose_name='Nivel de formacion '),
        ),
        migrations.AlterField(
            model_name='usui_inf_contac',
            name='ls_ha',
            field=models.IntegerField(choices=[(0, '8am 12pm'), (1, '2pm 6pm'), (2, '8am 12pm - 2pm 6pm')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='usui_inf_inst',
            name='sector',
            field=models.IntegerField(choices=[(0, 'Privado'), (1, 'Publico'), (2, 'xxx'), (3, 'zzzz')], default=0, max_length=1, verbose_name='sector de desempeño de la entidad o institución '),
        ),
        migrations.AlterField(
            model_name='usui_inf_inst',
            name='tipo_inst',
            field=models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0, max_length=1, verbose_name='Tipo de institución o entidad'),
        ),
        migrations.AlterField(
            model_name='usui_inf_inst',
            name='tipo_nuii',
            field=models.IntegerField(choices=[(0, 'NIT'), (1, 'RUT')], default=0, max_length=1, verbose_name='Tipo de Número de identificación Institucional'),
        ),
    ]
