# Generated by Django 3.1.7 on 2021-05-04 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_modpry', '0001_initial'),
        ('App_regpryi', '0001_initial'),
        ('App_gespry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inf_ges_pry',
            name='idproy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regpryi.inf_pry'),
        ),
        migrations.AddField(
            model_name='app_ges_pry',
            name='id_mod_pry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modpry.mod_pry'),
        ),
    ]
