# Generated by Django 3.1.7 on 2021-05-04 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_ev_pry',
            fields=[
                ('id_app_ev_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_app_ev_pry', models.CharField(max_length=40, verbose_name='nombre de la App Evaluación  ')),
                ('desc_app_ev_pry', models.CharField(max_length=40, verbose_name='descripcion de la App  ')),
                ('status_app_ev_pry', models.BooleanField(default=False, verbose_name='estatus de la App Evaluación de Proyectos ')),
            ],
            options={
                'verbose_name': 'app_ev_pry',
                'verbose_name_plural': 'app_ev_prys',
            },
        ),
        migrations.CreateModel(
            name='criterios',
            fields=[
                ('id_criterios_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_creterio', models.CharField(max_length=40, verbose_name='Nombre del criterio')),
                ('desc_criterio', models.CharField(max_length=40, verbose_name='Descripcion del criterio')),
                ('objetivo_lograr', models.CharField(max_length=40, verbose_name='Objetivo a lograr')),
                ('porcentage_calificacion', models.CharField(max_length=40, verbose_name='porcentaje de calificacion')),
            ],
            options={
                'verbose_name': 'criterios',
                'verbose_name_plural': 'criterioss',
            },
        ),
        migrations.CreateModel(
            name='criterios_pry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_logrado', models.BooleanField(default=False, verbose_name='si logro el objetivo')),
            ],
            options={
                'verbose_name': 'criterios_pry',
                'verbose_name_plural': 'criterios_prys',
            },
        ),
        migrations.CreateModel(
            name='evalucion_pry',
            fields=[
                ('id_evalucion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipos_evalucion', models.CharField(max_length=40, verbose_name='descripcion del tipo de evalucion ')),
                ('fech_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
            ],
            options={
                'verbose_name': 'evalucion_pry',
                'verbose_name_plural': 'evalucion_prys',
            },
        ),
        migrations.CreateModel(
            name='tipos_evalucion',
            fields=[
                ('id_ipos_evalucion', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_tipos_evalucion', models.CharField(max_length=40, verbose_name='Nombre del tipo de evalucion ')),
                ('desc_tipos_evalucion', models.CharField(max_length=40, verbose_name='descripcion del tipo de evalucion ')),
            ],
            options={
                'verbose_name': 'tipos_evalucion',
                'verbose_name_plural': 'tipos_evalucions',
            },
        ),
        migrations.CreateModel(
            name='rel_evalucion_pry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evalucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_evapry.evalucion_pry')),
            ],
            options={
                'verbose_name': 'rel_evalucion_pry',
                'verbose_name_plural': 'rel_evalucion_prys',
            },
        ),
    ]
