# Generated by Django 3.2 on 2021-04-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm_install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='app_mod',
            fields=[
                ('id_app', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, verbose_name='Título de la aplicacion: ')),
                ('desc', models.CharField(max_length=80, verbose_name='descricion de la aplicacion: ')),
                ('url_doc', models.URLField(verbose_name='Direción local a la documentación o manual de la aplicación')),
                ('version', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Versión de desarrollo de la aplicación: ')),
                ('ver_mod', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Versión de desarrollo de la aplicación: ')),
                ('activo', models.BooleanField(default=False, verbose_name='estatus de la aplicacion ')),
                ('instalada', models.BooleanField(default=False, verbose_name='¿La aplicación se encuentra instalada? ')),
                ('visible', models.BooleanField(default=False, verbose_name='¿Activa o desactiva la visibilidad de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'app_mod',
                'verbose_name_plural': 'app_mods',
            },
        ),
        migrations.CreateModel(
            name='conv_inv',
            fields=[
                ('id_conv', models.AutoField(primary_key=True, serialize=False)),
                ('val_min', models.PositiveSmallIntegerField(default=5, verbose_name='valor minimo: ')),
                ('val_max', models.PositiveSmallIntegerField(default=5, verbose_name='valor maximo: ')),
                ('fch_ini', models.DateField(verbose_name='Fecha de inicio Incripciones: ')),
                ('fch_fin', models.DateField(verbose_name='Fecha de Cierre de Inscripciones: ')),
                ('pltf', models.BooleanField(default=False, verbose_name='Se puede registrar desde la plataforma: ')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad ')),
                ('mod', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Modalidad ')),
                ('und_acdm', models.CharField(max_length=60, verbose_name='Nombre de la unidad académica ')),
                ('resp', models.CharField(max_length=60, verbose_name='Nombre de la persona responsable ')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo ')),
                ('nom_conv', models.CharField(max_length=60, verbose_name='Nombre de la convocatori ')),
                ('url_conv', models.URLField(max_length=80, verbose_name='sitio web donde se puede localizar los términos de al convocatoria')),
                ('url_insc', models.URLField(max_length=80, verbose_name='Url del formulario de inscripción')),
            ],
            options={
                'verbose_name': 'conv_inv',
                'verbose_name_plural': 'conv_invs',
            },
        ),
        migrations.CreateModel(
            name='curs_dict',
            fields=[
                ('id_cd', models.AutoField(primary_key=True, serialize=False)),
                ('instit', models.CharField(max_length=20, verbose_name='Nombre de la institucion académica donde dictó el curso. ')),
                ('tipo_form', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2)),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de fin')),
                ('certif', models.BooleanField(default=True, verbose_name='Posees Certificado')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad ')),
                ('mod', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Modalidad')),
                ('num_est', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes')),
                ('dur', models.IntegerField(verbose_name='Cantidad de estudiantes')),
                ('nom_curs', models.CharField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='Número total de horas académicas del curso')),
                ('mun_ciclos', models.IntegerField(verbose_name='cuántas veces se dictó el curso')),
                ('url_prog', models.URLField(verbose_name='Url del documento o sitio web ')),
            ],
            options={
                'verbose_name': 'curs_dict',
                'verbose_name_plural': 'curs_dicts',
            },
        ),
        migrations.CreateModel(
            name='curs_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instit', models.CharField(max_length=20, verbose_name='Nombre de la institucion académica ')),
                ('tipo_form_gr', models.IntegerField(choices=[(0, 'Seminario'), (1, 'Taller'), (2, 'Foro'), (3, 'Charla'), (4, 'Encuentro'), (5, 'Simposio'), (6, 'Panel'), (7, 'Conferencia'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Congreso'), (11, 'Socialización'), (12, 'Coloquio'), (13, 'Otro')], default=0, max_length=2)),
                ('fch_ini', models.DateField(verbose_name='fecha Inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha Fin ')),
                ('certif', models.BooleanField(default=True, verbose_name='Activo ')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais: ')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad ')),
                ('mod', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1)),
                ('num_est', models.PositiveSmallIntegerField(default=5, verbose_name='Cupo de Estudiantes o asistentes')),
                ('dur', models.PositiveSmallIntegerField(default=5, verbose_name='Número total de horas académicas del curso')),
                ('nom_curs', models.CharField(max_length=30, verbose_name='Nombre del Curso o evento académico. ')),
                ('mun_ciclos', models.PositiveSmallIntegerField(default=5, verbose_name='cuántas veces se realizará el curso o evento')),
                ('url_prog', models.URLField(verbose_name='página web o blog del grupo ')),
                ('inscr', models.URLField(null='False', verbose_name='Url del formulario de inscripción.')),
            ],
            options={
                'verbose_name': 'curs_ofer',
                'verbose_name_plural': 'curs_ofers',
            },
        ),
        migrations.CreateModel(
            name='discapacidad',
            fields=[
                ('id_disc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_disca', models.CharField(max_length=30, verbose_name='tipo de discapacidad ')),
                ('desc_disca', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'discapacidad',
                'verbose_name_plural': 'discapacidads',
            },
        ),
        migrations.CreateModel(
            name='etapa_gr',
            fields=[
                ('id_etp_gr', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20, verbose_name='Nombre del grupo  ')),
                ('fch_ini_nom', models.DateField(verbose_name='Fecha en la que se creó el grupo ')),
                ('fch_fin_nom', models.DateField(verbose_name='Fecha en la que se terminó el grupo')),
                ('vig', models.BooleanField(default=True, verbose_name='El nombre se encuentra vigente ')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla con la que se identificó(a) el grupo ')),
                ('url_arch', models.URLField(verbose_name='URL del sitio web ')),
                ('gruplac', models.URLField(blank='False', null='False', verbose_name='Url del GrupLac del grupo de Investigación con ese nombre si se está registrado en esa plataforma.')),
            ],
            options={
                'verbose_name': 'etapa_gr',
                'verbose_name_plural': 'etapa_grs',
            },
        ),
        migrations.CreateModel(
            name='ext_app',
            fields=[
                ('id_app_ext', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_app_ext', models.CharField(max_length=40, verbose_name='Título de la aplicacion: ')),
                ('mod_prin_app_ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
            ],
            options={
                'verbose_name': 'ext_app',
                'verbose_name_plural': 'ext_apps',
            },
        ),
        migrations.CreateModel(
            name='ext_mod',
            fields=[
                ('id_mod_ext', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_ext', models.CharField(max_length=40, verbose_name='Título de la aplicacion: ')),
            ],
            options={
                'verbose_name': 'ext_mod',
                'verbose_name_plural': 'ext_mods',
            },
        ),
        migrations.CreateModel(
            name='form_acad',
            fields=[
                ('id_fa', models.AutoField(primary_key=True, serialize=False)),
                ('instit', models.CharField(max_length=25, verbose_name='Nombre de la institucion ')),
                ('tipo_form', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2)),
                ('fch_ini', models.DateField(verbose_name='fecha de Inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de Fin')),
                ('certif', models.BooleanField(default=False, verbose_name='Posees Certificado')),
                ('nal', models.CharField(max_length=20, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad ')),
                ('mod', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1)),
                ('tit', models.CharField(max_length=20, verbose_name='Titulo obtenido ')),
                ('menc', models.CharField(max_length=20, verbose_name='Mensión ')),
                ('token', models.CharField(max_length=20, verbose_name='token de validación ')),
            ],
            options={
                'verbose_name': 'form_acad',
                'verbose_name_plural': 'form_acads',
            },
        ),
        migrations.CreateModel(
            name='form_acad_gr',
            fields=[
                ('id_form_acad_gr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_form', models.IntegerField(choices=[(0, 'Seminario'), (1, 'Taller'), (2, 'Foro'), (3, 'Charla'), (4, 'Encuentro'), (5, 'Simposio'), (6, 'Panel'), (7, 'Conferencia'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Congreso'), (11, 'Socialización'), (12, 'Coloquio'), (13, 'Otro')], default=0, max_length=2)),
                ('fch_ini', models.DateField(verbose_name='Fecha de inicio ')),
                ('fch_fin', models.DateField(verbose_name='Fecha de fin: ')),
                ('certif', models.BooleanField(default=True, verbose_name='Posees Ceertificado: ')),
                ('nal', models.CharField(max_length=25, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=25, verbose_name='Ciudad: ')),
                ('mod', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1)),
                ('asis', models.PositiveSmallIntegerField(default=5, verbose_name='Número de asistentes')),
                ('hora', models.PositiveSmallIntegerField(default=5, verbose_name=' Número de horas académicas')),
                ('mem', models.URLField(verbose_name='url de las memorias del tipo de formación')),
                ('token', models.CharField(max_length=30, verbose_name='Token de validación electrónica')),
            ],
            options={
                'verbose_name': 'form_acad_gr',
                'verbose_name_plural': 'form_acad_gr',
            },
        ),
        migrations.CreateModel(
            name='fuente_ins',
            fields=[
                ('id_rep', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0, max_length=1)),
                ('tipo_arch', models.IntegerField(choices=[(0, '.Zip'), (1, '.Gz'), (2, '.ded'), (3, '.exe'), (4, 'otro')], default=0, max_length=1)),
                ('url_loc', models.CharField(max_length=5, verbose_name='Dirección local: ')),
                ('url_rem', models.URLField(verbose_name='Drección remota ')),
                ('url', models.URLField(verbose_name='Drección local relativa ')),
                ('valid', models.BooleanField(default=False, verbose_name='¿fuente valida?')),
            ],
            options={
                'verbose_name': 'fuente_ins',
                'verbose_name_plural': 'fuente_inss',
            },
        ),
        migrations.CreateModel(
            name='func_app',
            fields=[
                ('id_func', models.AutoField(primary_key=True, serialize=False)),
                ('nom_func', models.CharField(max_length=30, verbose_name='Nombre de la función: ')),
                ('lib_func', models.CharField(max_length=30, verbose_name='Librería que contiene la función: ')),
                ('url_loc', models.URLField(verbose_name='Direción local a la documentación o manual de la aplicación')),
                ('com_exc', models.CharField(max_length=20, verbose_name='Comando de Ejecución de la Función: ')),
                ('text', models.CharField(max_length=20, verbose_name='Nombre de Función: ')),
                ('context', models.CharField(max_length=20, verbose_name='Contexto: ')),
                ('activa', models.BooleanField(default=False, verbose_name='¿Activa o desactiva.?')),
                ('indice', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'func_app',
                'verbose_name_plural': 'func_apps',
            },
        ),
        migrations.CreateModel(
            name='habilidades',
            fields=[
                ('id_hab', models.AutoField(primary_key=True, serialize=False)),
                ('nom_hab', models.CharField(max_length=20, verbose_name='Nombre de la habilidad')),
                ('desc', models.CharField(max_length=20, verbose_name='Descripción de la Habilidad')),
            ],
            options={
                'verbose_name': 'habilidades',
                'verbose_name_plural': 'habilidadess',
            },
        ),
        migrations.CreateModel(
            name='listado_aplicativo',
            fields=[
                ('id_aplicativo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_aplicativo', models.CharField(max_length=30, verbose_name='aplicativo nombre: ')),
                ('activoaplicativo', models.BooleanField(default=False, verbose_name='¿Activo o desactivo.?')),
            ],
            options={
                'verbose_name': 'listado_aplicativo',
                'verbose_name_plural': 'listado_aplicativo',
            },
        ),
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40, verbose_name='Título del módulo')),
                ('desc', models.CharField(max_length=50, verbose_name='descripcion del Módulo')),
                ('url_doc', models.URLField(verbose_name='Sitio url')),
                ('version', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Versión de desarrollo ')),
                ('activo', models.BooleanField(default=False, verbose_name='Status del Modulo ')),
                ('instalado', models.BooleanField(default=False, verbose_name='¿el módulo se encuentra instalado?')),
                ('visible', models.BooleanField(default=False, verbose_name='¿Activa o desactiva la visibilidad de la aplicacion.?')),
            ],
            options={
                'verbose_name': 'mod',
                'verbose_name_plural': 'mods',
            },
        ),
        migrations.CreateModel(
            name='param_config',
            fields=[
                ('id_param_config', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_param_config', models.CharField(max_length=40, verbose_name='Parametro ')),
            ],
            options={
                'verbose_name': 'param_config',
                'verbose_name_plural': 'param_configs',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permisos', models.AutoField(primary_key=True, serialize=False)),
                ('nom_permiso', models.CharField(max_length=30, verbose_name='permisos: ')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Activ o desactivo.?')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='prog_ofer',
            fields=[
                ('id_prog', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_form', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2)),
                ('fch_ini', models.DateField(verbose_name='fecha de inscripcion')),
                ('fch_fin', models.DateField(verbose_name='fecha de Cierre de la inscripcion')),
                ('certif', models.BooleanField(default=True, verbose_name='Posee certificado')),
                ('nal', models.CharField(max_length=30, verbose_name='Pais: ')),
                ('ciudad', models.CharField(max_length=40, verbose_name='Ciudad ')),
                ('mod', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual'), (2, 'Semipresencial'), (3, 'A distancia'), (4, 'Aprendizaje Acompañado')], default=0, max_length=1, verbose_name='MODALIDAD')),
                ('num_est', models.PositiveSmallIntegerField(default=5, verbose_name='cantidad d estudiantes ')),
                ('dur', models.PositiveSmallIntegerField(default=4, verbose_name='Número total de horas')),
                ('dur_sem', models.PositiveSmallIntegerField(default=4, verbose_name='Número total de semestres')),
                ('nom_prog', models.CharField(max_length=30, verbose_name='Nombre del Programa')),
                ('acred', models.BooleanField(default=True, verbose_name='El programa se encuentra acreditado')),
                ('ven_acrd', models.PositiveSmallIntegerField(default=5, verbose_name='Año de vencimiento de la acreditación')),
                ('url_prog', models.URLField(max_length=80, verbose_name='sitio web donde se puede localizar el programa')),
            ],
            options={
                'verbose_name': 'prog_ofer',
                'verbose_name_plural': 'prog_ofers',
            },
        ),
        migrations.CreateModel(
            name='red_soc',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_red', models.CharField(max_length=30, verbose_name='Dirección de Oficina (país, ciudad, dir) ')),
                ('usuario', models.CharField(max_length=20, verbose_name='Direcció n de Oficina (país, ciudad, dir) ')),
                ('url', models.URLField(verbose_name='Url de página principal dentro de la red.')),
                ('uso', models.CharField(max_length=20, verbose_name='Uso de la red (frecuente:0; moderado:1; poco frecuente:2; inactivo:3) ')),
                ('pub', models.BooleanField(default=False, verbose_name='acceso público de información de red')),
            ],
            options={
                'verbose_name': 'red_soc',
                'verbose_name_plural': 'red_socs',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('etq_rol', models.CharField(max_length=30, verbose_name='Etiqueta: ')),
                ('desc', models.CharField(max_length=30, verbose_name='Descripcion del Rol: ')),
                ('tipo', models.IntegerField(choices=[(0, 'Sistema'), (1, 'Módulo'), (2, 'Aplicación'), (3, 'Extensión'), (4, 'Otro')], default=0, max_length=1)),
                ('req_reg', models.BooleanField(default=False, verbose_name='¿Activa o desactiva.?')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
                ('id_ext_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.ext_app')),
                ('id_ext_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.ext_mod')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('id_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.listado_aplicativo')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'rols',
            },
        ),
        migrations.CreateModel(
            name='usu',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30, verbose_name='Nick: ')),
                ('passusu', models.CharField(max_length=30, verbose_name='Contraseña: ')),
                ('fch_regi', models.DateField(verbose_name='fecha de registro')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Activo o desactivado.?')),
                ('id_rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
            options={
                'verbose_name': 'usu',
                'verbose_name_plural': 'usus',
            },
        ),
        migrations.CreateModel(
            name='usugr',
            fields=[
                ('id_gr', models.AutoField(primary_key=True, serialize=False)),
                ('passgr', models.CharField(max_length=20, verbose_name='Descripcion ')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo ')),
                ('id_rol_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
                ('id_usu_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'usugr',
                'verbose_name_plural': 'usugr',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_gr',
            fields=[
                ('id_usugr', models.AutoField(primary_key=True, serialize=False)),
                ('cod_gr', models.PositiveSmallIntegerField(default=8, verbose_name=' código único de identificación del grupo')),
                ('tipo_gr', models.IntegerField(choices=[(0, 'Independiente'), (1, 'Reconocido Inst'), (2, 'Reconocido COLC'), (3, 'Semillero de Inv.'), (4, 'Comunidad'), (5, 'Estado del Arte')], default=0, max_length=1)),
                ('nal', models.CharField(max_length=40, verbose_name='Nacionalidad')),
                ('dir', models.CharField(max_length=40, verbose_name='Direccion de correspondencia ')),
                ('estado', models.IntegerField(choices=[(0, 'Creado'), (1, 'Desarrollo Temprano'), (2, 'Dearrollo Medio'), (3, 'Desarrollo Alto'), (4, 'Consolidado'), (5, 'Ramificado'), (6, 'Fusionado'), (7, 'Disgregado'), (8, 'Disuelto'), (9, 'liquidado'), (10, 'Abandonado')], default=0, max_length=2)),
                ('url_imag', models.URLField(verbose_name='url de la imagen o logo del grupo')),
                ('zona_hor', models.CharField(max_length=40, verbose_name='Zona Horaria')),
                ('id_etp_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.etapa_gr')),
            ],
            options={
                'verbose_name': 'usugr_inf_gr',
                'verbose_name_plural': 'usugr_inf_grs',
            },
        ),
        migrations.CreateModel(
            name='usui',
            fields=[
                ('id_usuinst', models.AutoField(primary_key=True, serialize=False)),
                ('passinst', models.CharField(max_length=15, verbose_name='Contraseña ')),
                ('fch_regi', models.DateField(verbose_name='fecha de registro de usurio: ')),
                ('activo', models.BooleanField(default=True, verbose_name=' estatus del usuario activo')),
                ('id_rol_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
                ('id_usu_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'usui',
                'verbose_name_plural': 'usuis',
            },
        ),
        migrations.CreateModel(
            name='valid_hab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esc', models.CharField(max_length=20, verbose_name='IDENTIFICADOR ')),
                ('val', models.CharField(max_length=20, verbose_name='RANGO ')),
                ('id_hab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.habilidades')),
                ('id_usu_val', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'valid_hab',
                'verbose_name_plural': 'valid_habs',
            },
        ),
        migrations.CreateModel(
            name='usuo_prog_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.prog_ofer')),
            ],
        ),
        migrations.CreateModel(
            name='usui_rol_actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
        ),
        migrations.CreateModel(
            name='usui_red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.red_soc')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
            ],
        ),
        migrations.CreateModel(
            name='usui_inf_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
            ],
        ),
        migrations.CreateModel(
            name='usui_inf_inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuii', models.CharField(max_length=30, verbose_name='número único de identificación institucional sin puntos')),
                ('tipo_nuii', models.IntegerField(choices=[(0, 'NIT'), (1, 'RUT')], default=0, max_length=1, verbose_name='Tipo de Número de identificación Institucional')),
                ('rs', models.CharField(max_length=30, verbose_name='Razón Social de la Institución')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla institucional')),
                ('repleg', models.CharField(max_length=60, verbose_name='Nombre Completo del representante legal')),
                ('nal', models.CharField(max_length=25, verbose_name='nacionalidad')),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio de la institución')),
                ('fch_reg', models.DateField(verbose_name='fecha de registro de la institución en al plataforma')),
                ('tipo_inst', models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0, max_length=1, verbose_name='Tipo de institución o entidad')),
                ('sector', models.IntegerField(choices=[(0, 'Privado'), (1, 'Publico'), (2, 'xxx'), (3, 'zzzz')], default=0, max_length=1, verbose_name='sector de desempeño de la entidad o institución ')),
                ('dir', models.TextField(verbose_name='direccion sede administrativa')),
                ('url_imag', models.URLField(verbose_name='url de la imagen institucional o logo')),
                ('zona_hor', models.CharField(max_length=60, verbose_name='Zona Horario internacional')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
            ],
            options={
                'verbose_name': 'usui_inf_inst',
                'verbose_name_plural': 'usui_inf_insts',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_nal', models.CharField(max_length=5, verbose_name='Indicativo telefónico de país')),
                ('tel', models.CharField(max_length=20, verbose_name='Número de telefono fijo')),
                ('cel', models.CharField(max_length=20, verbose_name='Número de telefono móvil')),
                ('email', models.EmailField(max_length=40, verbose_name='correo ')),
                ('cod_post', models.PositiveSmallIntegerField(default=8, verbose_name='código postal ')),
                ('ls_ha', models.IntegerField(choices=[(0, '8am 12pm'), (1, '2pm 6pm'), (2, '8am 12pm - 2pm 6pm')], default=0, max_length=1)),
                ('web', models.URLField(max_length=60, verbose_name=' dirección de página web o blog institucional')),
                ('dir_pri', models.TextField(verbose_name='Dirección de sede principal (país, ciudad, dir. ')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
            ],
            options={
                'verbose_name': 'usui_inf_contac',
                'verbose_name_plural': 'usui_inf_contacs',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.listado_aplicativo')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
            options={
                'verbose_name': 'usui_inf_apps',
                'verbose_name_plural': 'usui_inf_appss',
            },
        ),
        migrations.CreateModel(
            name='usui_inf_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelform', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2, verbose_name='Nivel de formacion ')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
            ],
            options={
                'verbose_name': 'usui_inf_acad',
                'verbose_name_plural': 'usui_inf_acads',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr_inf_gr')),
                ('ls_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.red_soc')),
            ],
        ),
        migrations.CreateModel(
            name='usugr_inf_contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_nal', models.CharField(max_length=20, verbose_name='Nacionalidad ')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefono oficina ')),
                ('cel', models.CharField(max_length=20, verbose_name='N° Celular ')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('cod_post', models.PositiveSmallIntegerField(default=5, verbose_name='Codigo Postal ')),
                ('ls_hr', models.IntegerField(choices=[(0, '8am 12pm'), (1, '2pm 6pm'), (2, '8am 12pm - 2pm 6pm')], default=0, max_length=1)),
                ('web', models.URLField(verbose_name='página web o blog del grupo ')),
                ('dir_offi', models.TextField(verbose_name='Direccion e oficina')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
            ],
            options={
                'verbose_name': 'usugr_inf_contac',
                'verbose_name_plural': 'usugr_inf_contacs',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.listado_aplicativo')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
            options={
                'verbose_name': 'usugr_inf_apps',
                'verbose_name_plural': 'usugr_inf_appss',
            },
        ),
        migrations.CreateModel(
            name='usugr_inf_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr_inf_gr')),
            ],
            options={
                'verbose_name': 'usugr_inf_acad',
                'verbose_name_plural': 'usugr_inf_acads',
            },
        ),
        migrations.CreateModel(
            name='usugr_form_acad_gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr_inf_gr')),
                ('ls_form_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.form_acad_gr')),
            ],
        ),
        migrations.CreateModel(
            name='usugr_curs_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr_inf_gr')),
                ('ls_cursofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.curs_ofer')),
            ],
        ),
        migrations.CreateModel(
            name='usu_nr',
            fields=[
                ('id_usu_nr', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres del integrante no registrado(a).')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos del integrante no registrado(a).')),
                ('cvlac', models.URLField(verbose_name='URL del CVlac del investigador(a).')),
                ('orcid', models.CharField(max_length=20, verbose_name='ID de ORCID del investigador(a).')),
                ('ggl', models.URLField(verbose_name='URL Google académico del investigador(a)')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
            options={
                'verbose_name': 'usu_nr',
                'verbose_name_plural': 'usu_nrs',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=20, verbose_name='Titulo obtenido ')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'usu_inf_prof',
                'verbose_name_plural': 'usu_inf_profs',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_pers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuip', models.CharField(max_length=30, verbose_name='número único de identificación personal ')),
                ('tipo_nuip', models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Cédula de Extranjería'), (3, 'Pasaporte'), (4, 'Permiso de Residencia')], default=0, max_length=1)),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres ')),
                ('apelllidos', models.CharField(max_length=60, verbose_name='Apellidos ')),
                ('nal', models.CharField(max_length=30, verbose_name='Nacionalidad ')),
                ('fch_naci', models.DateField(verbose_name='fecha de nacimiento')),
                ('gene', models.IntegerField(choices=[(0, 'Neutro'), (1, 'Femenino'), (2, 'Masculino'), (3, 'Intergénero'), (4, 'Transgénero'), (5, 'Sisgénero'), (6, 'Otro')], default=0, max_length=1)),
                ('ocup', models.CharField(max_length=30, verbose_name='Ocupacion ')),
                ('dir', models.CharField(max_length=100, verbose_name='Direccion ')),
                ('discap', models.BooleanField(default=False, verbose_name='¿Es una persona en condición de discapacidad?')),
                ('url_imag', models.URLField(verbose_name='url de la imagen personal.')),
                ('zona_hor', models.CharField(max_length=100, verbose_name='Zona Horaria ')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('tipo_discap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.discapacidad')),
            ],
            options={
                'verbose_name': 'usu_inf_pers',
                'verbose_name_plural': 'usu_inf_perss',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_hab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción ')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('ls_habs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.habilidades')),
            ],
            options={
                'verbose_name': 'usu_inf_hab',
                'verbose_name_plural': 'usu_inf_habs',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_nal', models.PositiveSmallIntegerField(verbose_name='Indicativo telefónico de país')),
                ('cel', models.CharField(max_length=30, verbose_name='Número de telefono móvil del usuario')),
                ('wa', models.CharField(max_length=30, verbose_name='Número de WhatsApp')),
                ('email', models.EmailField(max_length=30, verbose_name='Correo electrocico')),
                ('cod_post', models.PositiveSmallIntegerField(verbose_name='Número de código postal')),
                ('ls_ha', models.IntegerField(choices=[(0, '8am 12pm'), (1, '2pm 6pm'), (2, '8am 12pm - 2pm 6pm')], default=0, max_length=1)),
                ('web', models.URLField(verbose_name='dirección de página web o blog personal')),
                ('dir_offi', models.CharField(max_length=100, verbose_name='Dirección de Ofiina (país, ciudad, dir) ')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'usu_inf_contac',
                'verbose_name_plural': 'usu_inf_contacs',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.listado_aplicativo')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('rol_sis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
            options={
                'verbose_name': 'usu_inf_apps',
                'verbose_name_plural': 'usu_inf_appss',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelform', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0, max_length=2)),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'usu_inf_acad',
                'verbose_name_plural': 'usu_inf_acads',
            },
        ),
        migrations.CreateModel(
            name='rol_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Activ o desactivo.?')),
                ('id_permisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
            options={
                'verbose_name': 'rol_permiso',
                'verbose_name_plural': 'rol_permisos',
            },
        ),
        migrations.CreateModel(
            name='rl_usui_usugr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
                ('ls_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usui_usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
                ('ls_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usui_conv_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui')),
                ('ls_conv_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.conv_inv')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usugr_inf_rol_Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usugr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
                ('rol_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('ls_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.red_soc')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_prof_empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('ls_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.curs_dict')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_form_acad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('ls_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.form_acad')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_contac_curs_dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('ls_cursdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.curs_dict')),
            ],
        ),
        migrations.CreateModel(
            name='rl_usu_inf_apps_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
                ('rol_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('ls_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_param_cnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('ls_param_cnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.param_config')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('ls_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.func_app')),
            ],
        ),
        migrations.CreateModel(
            name='rl_mod_app_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('ls_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
            ],
        ),
        migrations.CreateModel(
            name='rl_fuente_ins_param_cnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_param_cnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.param_config')),
                ('id_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.fuente_ins')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
                ('ls_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.rol')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_param_cnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
                ('ls_param_cnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.param_config')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
                ('ls_mods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
            ],
        ),
        migrations.CreateModel(
            name='rl_app_mod_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
                ('ls_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.func_app')),
            ],
        ),
        migrations.CreateModel(
            name='rel_usugr_ls_usu_nr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
                ('ls_int_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu_nr')),
            ],
        ),
        migrations.CreateModel(
            name='rel_usugr_ls_usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
                ('ls_int_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
        ),
        migrations.CreateModel(
            name='rel_usugr_ls_etp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr')),
                ('ls_etp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.etapa_gr')),
            ],
        ),
        migrations.AddField(
            model_name='prog_ofer',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui'),
        ),
        migrations.CreateModel(
            name='mod_adm',
            fields=[
                ('sesion', models.AutoField(primary_key=True, serialize=False)),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('id_usu_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'mod_adm',
                'verbose_name_plural': 'mod_adms',
            },
        ),
        migrations.CreateModel(
            name='log_mod_rol',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.URLField(verbose_name='Drección local relativa ')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
            ],
            options={
                'verbose_name': 'log_mod_rol',
                'verbose_name_plural': 'log_mod_rols',
            },
        ),
        migrations.CreateModel(
            name='log_acc_pltf',
            fields=[
                ('id_acc_pltf', models.AutoField(primary_key=True, serialize=False)),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de fin')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'log_acc_pltf',
                'verbose_name_plural': 'log_acc_pltfs',
            },
        ),
        migrations.CreateModel(
            name='log_acc_mod',
            fields=[
                ('id_log_acces', models.AutoField(primary_key=True, serialize=False)),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de fin')),
                ('id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'log_acc_mod',
                'verbose_name_plural': 'log_acc_mods',
            },
        ),
        migrations.AddField(
            model_name='form_acad',
            name='id_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu'),
        ),
        migrations.AddField(
            model_name='ext_mod',
            name='mod_prin_ext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod'),
        ),
        migrations.CreateModel(
            name='empleos',
            fields=[
                ('id_empl', models.AutoField(primary_key=True, serialize=False)),
                ('instit', models.CharField(max_length=20, verbose_name='Nombre de la institucion ')),
                ('nom_cargo', models.CharField(max_length=20, verbose_name='Nombre del Cargo ')),
                ('fch_ini', models.DateField(verbose_name='fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='fecha de Fin')),
                ('certif', models.BooleanField(default=False, verbose_name='Posees certificado')),
                ('nal', models.CharField(max_length=20, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad ')),
                ('tipo_contr', models.IntegerField(choices=[(0, 'Término Indefinido'), (1, 'Término Fijo'), (2, 'Temporal'), (3, 'Orden de Servicio'), (4, 'Contrato de Obra'), (5, 'Asesoría'), (6, 'Consultoría'), (7, 'independiente')], default=0, max_length=1)),
                ('tit', models.CharField(max_length=20, verbose_name='Titulo obtenido ')),
                ('menc', models.CharField(max_length=20, verbose_name='Mensión de honor ')),
                ('token', models.CharField(max_length=20, verbose_name='Token de validación electrónica  ')),
                ('ret', models.CharField(max_length=20, verbose_name=' Motivo del retiro ')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu')),
            ],
            options={
                'verbose_name': 'empleos',
                'verbose_name_plural': 'empleoss',
            },
        ),
        migrations.AddField(
            model_name='curs_dict',
            name='id_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usu'),
        ),
        migrations.AddField(
            model_name='conv_inv',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usui'),
        ),
        migrations.CreateModel(
            name='app_reg_usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la app ')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripcion ')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo ')),
                ('app_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
            ],
            options={
                'verbose_name': 'app_reg_usu',
                'verbose_name_plural': 'app_reg_usus',
            },
        ),
        migrations.CreateModel(
            name='app_reg_ins',
            fields=[
                ('app_reg_ins', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_app_reg_ins', models.CharField(max_length=20, verbose_name='Nombre  ')),
                ('desc_app_reg_ins', models.CharField(max_length=20, verbose_name='Descripcion  ')),
                ('status_app_reg_ins', models.BooleanField(default=False, verbose_name='Activo ')),
                ('id_aplicacion_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod')),
            ],
            options={
                'verbose_name': 'app_reg_ins',
                'verbose_name_plural': 'app_reg_inss',
            },
        ),
        migrations.CreateModel(
            name='app_reg_gr',
            fields=[
                ('id_app_reg_gr', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='Descripcion.')),
                ('id_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.app_mod')),
            ],
            options={
                'verbose_name': 'app_reg_gr',
                'verbose_name_plural': 'app_reg_grs',
            },
        ),
        migrations.AddField(
            model_name='app_mod',
            name='mod_prin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.mod'),
        ),
    ]
