# Generated by Django 3.2 on 2021-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAdm', '0002_auto_20210419_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usui_inf_inst',
            name='tipo_nuii',
            field=models.IntegerField(choices=[(0, 'NIT'), (1, 'RUT')], default=0, verbose_name='Tipo de Número de identificación Institucional'),
        ),
    ]
