# Generated by Django 3.2 on 2021-04-19 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moduloAdm', '0004_auto_20210419_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usu_inf_pers',
            name='id_usu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
