# Generated by Django 3.2 on 2021-04-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAdm', '0008_auto_20210420_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='usugr_inf_gr',
            name='id_grupo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moduloAdm.usugr'),
        ),
    ]
