# Generated by Django 3.2 on 2021-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAdm', '0009_usugr_inf_gr_id_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usugr_inf_gr',
            name='id_gr_padre',
            field=models.CharField(default=0, max_length=40, verbose_name='grupo padre'),
        ),
    ]
