# Generated by Django 3.2 on 2021-04-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administr', '0004_auto_20210416_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='mod_loz_act',
            fields=[
                ('idAct', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Act', models.CharField(max_length=60, verbose_name='identifican como actores')),
                ('Act_suest', models.CharField(max_length=50, verbose_name='Actores Supraestatales ')),
                ('Act_est', models.CharField(max_length=50, verbose_name='Actores Estatales ')),
                ('Rol', models.CharField(max_length=2, verbose_name='Los actores asumen roles ')),
            ],
            options={
                'verbose_name': 'mod_loz_act',
                'verbose_name_plural': 'mod_loz_acts',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_algrtm_Inst',
            fields=[
                ('id_algrtm_Inst', models.AutoField(primary_key=True, serialize=False)),
                ('Al_Instcol', models.IntegerField()),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_auto_adva',
            fields=[
                ('idAuto_Advo', models.AutoField(primary_key=True, serialize=False)),
                ('Per_jur', models.IntegerField()),
                ('Patr_Aut', models.IntegerField()),
                ('Grad', models.IntegerField(choices=[(0, 'Central'), (1, 'Descentralizada'), (2, 'Desconcentrada')], default=0, max_length=1)),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_ent_est',
            fields=[
                ('id_ent', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ent', models.CharField(max_length=70, verbose_name='Nombre de la Entidad')),
                ('sigla_ent', models.CharField(max_length=40, verbose_name='Sigla de la Entidad')),
                ('rama_pod', models.IntegerField(choices=[(0, 'Ejecutivo'), (1, 'Legislativo'), (2, 'Judicial'), (3, 'Organismo de Control'), (4, 'Organización electoral')], default=0, max_length=1)),
                ('tipo_ent', models.IntegerField(choices=[(0, 'Adscrita'), (1, 'Vinculada'), (2, 'Cabeza de Sector')], default=0, max_length=1)),
                ('niv_sec_pub', models.IntegerField(choices=[(0, 'Central'), (1, 'Descentralizado'), (2, 'Desconcentrado')], default=0, max_length=1)),
                ('niv_trtrial', models.IntegerField(choices=[(0, 'Internacional'), (1, 'Nacional'), (2, 'Regional'), (3, 'Departamental'), (4, 'Municipal'), (5, 'Distrito Especial'), (6, 'Distrito Capital'), (7, 'Localidad'), (8, 'Vereda'), (9, 'Corregimiento'), (10, 'Intendencia de policia'), (11, 'Territorio Comunidad Indígena'), (12, 'Territorio Étnico'), (13, 'Extraterritorial')], default=0, max_length=2)),
                ('fecha_ini', models.DateField(verbose_name='Fecha de creación de la Entidad')),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_norma',
            fields=[
                ('id_norma', models.AutoField(primary_key=True, serialize=False)),
                ('Sec', models.CharField(max_length=60, verbose_name='Sector al cual pertenece la entidad ')),
                ('Ram_pod', models.IntegerField(choices=[(0, 'Ejecutivo'), (1, 'Legislativo'), (2, 'Judicial'), (3, 'Organismo de Control'), (4, 'Organización electoral')], default=0)),
                ('Niv_Terial', models.IntegerField(choices=[(0, 'Internacional'), (1, 'Nacional'), (2, 'Regional'), (3, 'Departamental'), (4, 'Municipal'), (5, 'Distrito Especial'), (6, 'Distrito Capital'), (7, 'Localidad'), (8, 'Vereda'), (9, 'Corregimiento'), (10, 'Intendencia de policia'), (11, 'Territorio Comunidad Indígena'), (12, 'Territorio Étnico'), (13, 'Extraterritorial')], default=0)),
            ],
            options={
                'verbose_name': 'mod_loz_norma',
                'verbose_name_plural': 'mod_loz_normas',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_sect_juradm',
            fields=[
                ('id_sector_juradm', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sector_juradmin', models.CharField(max_length=45, verbose_name='Nombre del sector Jurídico administrativo')),
                ('fecha_ini', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'mod_loz_sect_juradm',
                'verbose_name_plural': 'mod_loz_sect_juradms',
            },
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('idPro', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_pro', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='Proy',
            fields=[
                ('idProy', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Proy', models.CharField(max_length=88, verbose_name='Nombre completo y oficial del Proy :')),
                ('Tip_acc', models.CharField(max_length=100, verbose_name='Tipo de acción :')),
                ('Pobl', models.CharField(max_length=90, verbose_name='Poblacion:')),
                ('Niv_trial', models.IntegerField(choices=[(0, 'Internacional'), (1, 'Nacional'), (2, 'Regional'), (3, 'Departamental'), (4, 'Municipal'), (5, 'Distrito Especial'), (6, 'Distrito Capital'), (7, 'Localidad'), (8, 'Vereda'), (9, 'Corregimiento'), (10, 'Intendencia de policia'), (11, 'Territorio Comunidad Indígena'), (12, 'Territorio Étnico'), (13, 'Extraterritorial')], default=0)),
                ('Nom_UO', models.CharField(max_length=60, verbose_name='Nombre de la Unidad Organizacional:')),
                ('Nom_Ent', models.CharField(max_length=60, verbose_name='Nombre de la Entidad:')),
                ('Per', models.CharField(max_length=60, verbose_name='Periodo de tiempo ')),
                ('MV', models.IntegerField()),
                ('Obj_proy', models.CharField(max_length=200, verbose_name='Objetivos que orientan el proyecto.')),
            ],
            options={
                'verbose_name': 'Proy',
                'verbose_name_plural': 'Proys',
            },
        ),
        migrations.CreateModel(
            name='Ref_doc',
            fields=[
                ('idRef_doc', models.AutoField(primary_key=True, serialize=False)),
                ('Tip_Doc', models.IntegerField(choices=[(0, 'Documento convencional'), (1, 'Documento no convencional')], default=0, max_length=1)),
                ('Cl_Doc', models.CharField(max_length=45, verbose_name='Clase documental')),
                ('Tt_Gral', models.CharField(max_length=45, verbose_name='Título general')),
                ('Tt_esp', models.CharField(max_length=45, verbose_name='Título Específico:')),
                ('Au_Gral', models.CharField(max_length=45, verbose_name='Autor (es) generales:')),
                ('Au_eps', models.CharField(max_length=45, verbose_name='Autor (es) específicos:')),
                ('Pag_Vol', models.CharField(max_length=45, verbose_name='Páginas y o volúmenes')),
            ],
            options={
                'verbose_name': 'Ref_doc',
                'verbose_name_plural': 'Ref_docs',
            },
        ),
        migrations.CreateModel(
            name='U_GP',
            fields=[
                ('idUn_Geopol', models.AutoField(primary_key=True, serialize=False)),
                ('Sec_jur_advo', models.CharField(max_length=50, verbose_name='Sector Jurìdico Admimnistrativo')),
                ('idEnt', models.CharField(max_length=50, verbose_name='entidad publica')),
                ('Nv_Trial', models.IntegerField(choices=[(0, 'Internacional'), (1, 'Nacional'), (2, 'Regional'), (3, 'Departamental'), (4, 'Municipal'), (5, 'Distrito Especial'), (6, 'Distrito Capital'), (7, 'Localidad'), (8, 'Vereda'), (9, 'Corregimiento'), (10, 'Intendencia de policia'), (11, 'Territorio Comunidad Indígena'), (12, 'Territorio Étnico'), (13, 'Extraterritorial')], default=0)),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='Un_Trial',
            fields=[
                ('idUn_Trial', models.AutoField(primary_key=True, serialize=False)),
                ('Un_Trialcol', models.IntegerField()),
                ('desc_Trial', models.CharField(max_length=100, verbose_name='Descripcion ')),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='Sec_Jur_Advo',
            fields=[
                ('idSec_Jur_Adv', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Sec_Jur_Advo', models.CharField(max_length=60, verbose_name='Nombre del Sector Jurídico Administrativo:')),
                ('Sig_Sec_Jur_Advo', models.CharField(max_length=60, verbose_name='Sigla del Sector Jurídico Administrativo')),
                ('idAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_act')),
                ('idEnt_Est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_ent_est')),
                ('idU_GP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.u_gp')),
            ],
            options={
                'verbose_name': 'Sec_Jur_Advo',
                'verbose_name_plural': 'Sec_Jur_Advos',
            },
        ),
        migrations.CreateModel(
            name='rl_entidad_norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_ent_est')),
                ('id_norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_norma')),
            ],
            options={
                'verbose_name': 'rl_entidad_norma',
                'verbose_name_plural': 'rl_entidad_normas',
            },
        ),
        migrations.CreateModel(
            name='rel_jrquia_v_obj',
            fields=[
                ('id_rel_jrquia_obj', models.AutoField(primary_key=True, serialize=False)),
                ('id_rel_jrquia', models.CharField(max_length=60, verbose_name='Identificador de la jerarquía:')),
                ('id_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_ent_est')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'rel_jrquia_v_obj',
                'verbose_name_plural': 'rel_jrquia_v_objs',
            },
        ),
        migrations.CreateModel(
            name='rel_histo_v_obj',
            fields=[
                ('id_rel_histo_obj', models.AutoField(primary_key=True, serialize=False)),
                ('id_histo', models.CharField(max_length=45, verbose_name='Historico :')),
                ('id_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_ent_est')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administr.usu')),
            ],
            options={
                'verbose_name': 'mod_loz_algrtm_Inst',
                'verbose_name_plural': 'mod_loz_algrtm_Insts',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_uo',
            fields=[
                ('id_uo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_uo', models.CharField(max_length=125, verbose_name='Nombre de la Unidad Organizacional:')),
                ('sigla_uo', models.CharField(max_length=25, verbose_name='Sigla de la Unidad Organizacional:')),
                ('id_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_ent_est')),
                ('id_sec_juradm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_sect_juradm')),
                ('norma_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_norma')),
            ],
            options={
                'verbose_name': 'mod_loz_uo',
                'verbose_name_plural': 'mod_loz_uos',
            },
        ),
        migrations.CreateModel(
            name='mod_loz_func',
            fields=[
                ('id_func', models.AutoField(primary_key=True, serialize=False)),
                ('cont_func', models.CharField(max_length=500, verbose_name='Transcribir (Sin Modificaciones) el contenido de la función. ')),
                ('tipo_obj_rel', models.IntegerField(choices=[(0, 'Entidad'), (1, 'Sector Jurídico Administrativo'), (2, 'Unidad Organizacional')], default=0, max_length=1)),
                ('id_norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_norma')),
                ('id_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloDpp.mod_loz_ent_est')),
            ],
            options={
                'verbose_name': 'mod_loz_func',
                'verbose_name_plural': 'mod_loz_funcs',
            },
        ),
    ]
