# Generated by Django 3.1.7 on 2021-05-04 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_modadm', '0001_initial'),
        ('App_regusugr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='proc_inv',
            fields=[
                ('id_proc', models.AutoField(primary_key=True, serialize=False)),
                ('instit', models.CharField(max_length=60, verbose_name='Nombre de la institucion')),
                ('clas_inv', models.IntegerField(choices=[(0, 'Estatal'), (1, 'Privada'), (2, 'Personal'), (3, 'Comunitaria'), (4, 'Mixta PUBPRV'), (5, 'Mixta PUBPER'), (6, 'Mixta PUBCOM'), (7, 'Otra')])),
                ('fch_ini', models.DateField(verbose_name='Fecha de inicio')),
                ('fch_fin', models.DateField(verbose_name='Fecha de fin')),
                ('certif', models.BooleanField(default=True, verbose_name='Posees certificado ')),
                ('nal', models.CharField(max_length=35, verbose_name='Pais ')),
                ('ciudad', models.CharField(max_length=40, verbose_name='Ciudad ')),
                ('rol_inv', models.IntegerField(choices=[(0, 'Sin Información'), (1, 'Investigador(a) Principal'), (2, 'Investigador(a) Senior'), (3, 'Investigador(a) Asociado(a)'), (4, 'Investigador(a) Junior'), (5, 'Investigador(a) Emérito(a)'), (6, 'Jóven Investigador(a)'), (7, 'Auxiliar de Investigación'), (8, 'Investigador(a) independiente')])),
                ('num_intg', models.PositiveSmallIntegerField(default=5, verbose_name='#Número de integrantes del equipo de investigación.')),
                ('horas', models.PositiveSmallIntegerField(default=5, verbose_name='Número de horas semanales dedicadas al proyecto')),
                ('ciclos', models.PositiveSmallIntegerField(default=5, verbose_name='cuántas veces se dictó el curso')),
                ('url_prog', models.URLField(max_length=80, verbose_name='Sitio web donde se puede localizar el programa del curso ')),
                ('id_grup_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusugr.usugr')),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proc_inv',
                'verbose_name_plural': 'proc_invs',
            },
        ),
        migrations.CreateModel(
            name='prod_inv',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('pub', models.BooleanField(default=False, verbose_name='El producto se encuentra publicado')),
                ('fch_real', models.DateField(verbose_name='Fecha de realización ')),
                ('fch_pub', models.DateField(default=False, verbose_name='fecha de publicación ')),
                ('reg', models.BooleanField(default=False, verbose_name='El producto se encuentra registrado en Plataforma de Colciencias ')),
                ('colab', models.BooleanField(default=False, verbose_name='El producto se realizó en colaboración de otros(as), ')),
                ('res_inv', models.BooleanField(default=False, verbose_name='El producto es resultado de un proyecto de investigación ')),
                ('horas', models.IntegerField(verbose_name='Número total de horas dedicadas al producto ')),
                ('url_prod', models.URLField(max_length=40, verbose_name='sitio web donde se puede localizar  ')),
                ('form', models.IntegerField(choices=[(0, '.Zip'), (1, '.Gz'), (2, '.ded'), (3, '.exe'), (4, 'otro')], default=0)),
                ('rep_pub', models.BooleanField(default=True, verbose_name='El archvio digita ')),
                ('id_proc_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.proc_inv')),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prod_inv',
                'verbose_name_plural': 'prod_invs',
            },
        ),
        migrations.CreateModel(
            name='red_div',
            fields=[
                ('id_red_div', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_red', models.CharField(max_length=60, verbose_name='Nombre de la red ')),
                ('usuario', models.CharField(max_length=60, verbose_name='Nick ')),
                ('url', models.URLField(max_length=60, verbose_name='Url de página principal dentro de la red ')),
                ('uso', models.IntegerField(choices=[(0, 'frecuente'), (1, 'moderado'), (2, 'poco frecuente'), (3, 'inactivo')], default=0, verbose_name='Uso de la red ')),
                ('pub', models.BooleanField(default=False, verbose_name='Acceso público de información de red ')),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'red_div',
                'verbose_name_plural': 'red_divs',
            },
        ),
        migrations.CreateModel(
            name='tipo_prod_inv',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_produccion', models.CharField(max_length=40, verbose_name='tipo de produccion.')),
                ('desc_produccion', models.CharField(max_length=40, verbose_name='Descripcion: ')),
            ],
            options={
                'verbose_name': 'tipo_prod_inv',
                'verbose_name_plural': 'tipo_prod_invs',
            },
        ),
        migrations.CreateModel(
            name='usu_inf_inv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cvlac', models.URLField(verbose_name=' URL del CVlac del investigador(a)..')),
                ('orcid', models.CharField(max_length=40, verbose_name='ID de ORCID del investigador(a). ')),
                ('ggl', models.URLField(verbose_name='URL Google académico del investigador(a).')),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.rol')),
            ],
            options={
                'verbose_name': 'usu_inf_inv',
                'verbose_name_plural': 'usu_inf_invs',
            },
        ),
        migrations.CreateModel(
            name='rl_usu_inf_inv_proc_inv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.proc_inv')),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rl_usu_inf_inv_proc_inv',
                'verbose_name_plural': 'rl_usu_inf_inv_proc_invs',
            },
        ),
        migrations.CreateModel(
            name='rl_usu_inf_inv_ls_red_div',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ls_red_div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.red_div')),
            ],
            options={
                'verbose_name': 'rl_usu_inf_inv_ls_red_div',
                'verbose_name_plural': 'rl_usu_inf_inv_ls_red_divs',
            },
        ),
        migrations.CreateModel(
            name='rl_prod_usu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.prod_inv')),
            ],
            options={
                'verbose_name': 'rl_prod_usu',
                'verbose_name_plural': 'rl_prod_usus',
            },
        ),
        migrations.AddField(
            model_name='prod_inv',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.tipo_prod_inv'),
        ),
    ]
