# Generated by Django 3.1.7 on 2021-05-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_regppi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_modadm', '0002_auto_20210507_1808'),
        ('App_regusugr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usu_inf_inv',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usu_inf_inv',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.rol'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_inv_proc_inv',
            name='id_proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.proc_inv'),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_inv_proc_inv',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_inv_ls_red_div',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usu_inf_inv_ls_red_div',
            name='ls_red_div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.red_div'),
        ),
        migrations.AddField(
            model_name='rl_prod_usu',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_prod_usu',
            name='prod_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.prod_inv'),
        ),
        migrations.AddField(
            model_name='red_div',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prod_inv',
            name='id_proc_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.proc_inv'),
        ),
        migrations.AddField(
            model_name='prod_inv',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prod_inv',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regppi.tipo_prod_inv'),
        ),
        migrations.AddField(
            model_name='proc_inv',
            name='id_grup_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusugr.usugr'),
        ),
        migrations.AddField(
            model_name='proc_inv',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
