# Generated by Django 3.1.7 on 2021-05-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_regprgi', '0002_auto_20210507_1808'),
        ('App_regpryi', '0002_auto_20210507_1808'),
        ('App_regusui', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_regusugr', '0002_auto_20210507_1808'),
        ('App_regusu', '0002_auto_20210507_1808'),
        ('App_modadm', '0002_auto_20210507_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='usui',
            name='id_usu_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usuo_prog_ofer',
            name='id_prog_ofer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_regusui.prog_ofer'),
        ),
        migrations.AddField(
            model_name='rl_usuo_prog_ofer',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_usugr',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_usugr',
            name='ls_usugr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusugr.usugr'),
        ),
        migrations.AddField(
            model_name='rl_usui_usu',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_usu',
            name='ls_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rl_usui_rol_actual',
            name='id_usui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_rol_actual',
            name='rol_sis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_modadm.rol'),
        ),
        migrations.AddField(
            model_name='rl_usui_red_social',
            name='id_red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusu.red_soc'),
        ),
        migrations.AddField(
            model_name='rl_usui_red_social',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_pry',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_pry',
            name='ls_pry_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regpryi.inf_pry'),
        ),
        migrations.AddField(
            model_name='rl_usui_prod',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_prod',
            name='ls_prod_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regprgi.inf_prog_inv'),
        ),
        migrations.AddField(
            model_name='rl_usui_inf_acad',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_conv_inv',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='rl_usui_conv_inv',
            name='ls_conv_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.conv_inv'),
        ),
        migrations.AddField(
            model_name='prog_ofer',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='conv_inv',
            name='id_usui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_regusui.usui'),
        ),
        migrations.AddField(
            model_name='app_reg_ins',
            name='id_aplicacion_administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_modadm.mod'),
        ),
    ]
