# Generated by Django 3.1.7 on 2021-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_reg_pry',
            fields=[
                ('id_app_reg_pry', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_app_reg_pry', models.CharField(max_length=40, verbose_name='nombre de la App Registro ')),
                ('desc_app_reg_pry', models.CharField(max_length=40, verbose_name='Descripcion de la Ap  id_grup_bd = p ')),
                ('status_app_reg_pry', models.BooleanField(default=True, verbose_name='Estatus de la aplicacion')),
            ],
            options={
                'verbose_name': 'app_reg_pry',
                'verbose_name_plural': 'app_reg_prys',
            },
        ),
        migrations.CreateModel(
            name='inf_pry',
            fields=[
                ('id_pry', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_pry', models.CharField(max_length=40, verbose_name='codigo ')),
                ('nombre_archivo', models.CharField(max_length=40, verbose_name='Nombre  ')),
                ('url_archivo', models.URLField(verbose_name=' Url del archivo del proyecto.')),
                ('titulo_pry', models.CharField(max_length=40, verbose_name='Título del proyecto.  ')),
                ('num_inv', models.IntegerField(verbose_name='Número de investigadores(as) involucrados en el proyecto')),
                ('prom_frm', models.IntegerField(choices=[(0, 'Universitaria'), (1, 'Especializacion'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'PHD'), (5, 'Posdoctorado'), (6, 'Básica Secundaria'), (7, 'Básica Primaria'), (8, 'Diplomado'), (9, 'Curso Corto'), (10, 'Técnica'), (11, 'tecnológica'), (12, 'Curso libre')], default=0)),
                ('conv', models.CharField(max_length=40, verbose_name='Convenio propuesto  ')),
                ('dur', models.IntegerField(verbose_name='Duración del proyecto valores dentro de un rango.')),
                ('und_dur', models.IntegerField(choices=[(0, 'Seg'), (1, 'Min'), (2, 'Horas'), (3, 'Meses'), (4, 'Años')], default=0)),
                ('geo', models.CharField(max_length=40, verbose_name='Aŕea geográfica que abarca el proyecto.')),
                ('resu', models.TextField(verbose_name='Resumen del proyecto.')),
                ('url_ap', models.URLField(verbose_name=' Url de la imágen del árbol de problemas.')),
                ('url_ao', models.URLField(verbose_name='Url de la imágen del árbol de objetivos.')),
                ('pobl_bnd', models.IntegerField(verbose_name='Tamaño de la población beneficiaria directa del proyecto.')),
                ('pobl_bni', models.IntegerField(verbose_name='Tamaño de la población beneficiaria indirecta .')),
                ('obj_gen', models.CharField(max_length=40, verbose_name='Objetivo general del proyecto..')),
                ('obj_esp', models.CharField(max_length=40, verbose_name='Objetivos específicos del proyecto.')),
            ],
            options={
                'verbose_name': 'inf_pry',
                'verbose_name_plural': 'inf_prys',
            },
        ),
        migrations.CreateModel(
            name='tipo_estud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tipos_pry',
            fields=[
                ('id_tipoproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_tipoproyecto', models.CharField(max_length=40, verbose_name='tipo de proyecto.')),
                ('desc_tipoproyecto', models.CharField(max_length=40, verbose_name='Descripcion: ')),
            ],
            options={
                'verbose_name': 'tipos_pry',
                'verbose_name_plural': 'tipos_prys',
            },
        ),
    ]
